# Generated by Django 4.2 on 2023-04-25 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='研究室名')),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '研究室',
                'verbose_name_plural': '研究室',
            },
        ),
        migrations.CreateModel(
            name='AffiliationLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTeacher', models.BooleanField(default=False, verbose_name='教員')),
                ('laboratory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '所属研究室',
                'verbose_name_plural': '所属研究室',
            },
        ),
    ]
